name: Page Automator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: eskatos/gradle-command-action@v1
        with:
          arguments: build

      - name: Use Node.js 15.x
        uses: actions/setup-node@v1
        with:
          node-version: 15.x

      - name: setup git config
        run: |
          git config user.name "Hoarfroster Bot"
          git config user.email "<penguin.zhang@qq.com>"

      - uses: actions/checkout@master
        with:
          repository: PassionPenguin/PageGenerator
          path: ./page-generator

      - uses: actions/checkout@master
        with:
          path: ./documents

      - name: Generate Structure
        run: |
          java -jar page-generator/build/libs/PageGenerator.jar --input=./documents
          cd ./documents
          if [[ -n $(git status -uno --porcelain) ]]
          then
            git add *
            git commit -m "Generate Structure"
            git push origin master --force
          fi

      - name: NPM Install
        run: |
          npm i -g markdown-html-gen
          npm i -g minify

      - name: Generate HTML Pages with Markdown Files
        run: |
          cd documents
          for f in documents/*.md
            do
              htmlpath=${f/documents/archive}
              htmlpath=${htmlpath/md/html}
              if [ ! -f htmlpath ]; then
                md2html "$f" -o ./archive
                echo "Generated $htmlpath"
              fi
            done


          if [[ -n $(git status -uno --porcelain) ]]
          then
            git add *
            git commit -m "Build Pages"
            git push origin master --force
          fi
