# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@master
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm i -g markdown-html-gen
    - run: cd documents && for f in *.md; do md2html -o ../archive $f; done
    - name: setup git config
      run: |
        git config user.name "Hoarfroster Bot"
        git config user.email "<penguin.zhang@qq.com>"
    - name: commit
      run: |
        # Stage the file, commit and push
        git add *
        git commit -m "Build Resources"
        git push origin master
