name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@master
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: |
          npm i -g markdown-html-gen
          npm i ls-minifier -g
          cd documents
          # documents/*.md => archive/*.html
          cd ../archive
          ls-minifier *.html --silent --override --html-compressor=html-minifier
          for f in *.md; do md2html -o ../archive $f; done
          # exit if no files need to be committed
          [[ -z $(git status -uno --porcelain) ]] && echo "this branch is clean, no need to push..." && kill -SIGINT $$;
          
    - name: setup git config
      run: |
        git config user.name "Hoarfroster Bot"
        git config user.email "<penguin.zhang@qq.com>"
        
    - uses: nadock/verified_commits_check@v1
      
    - name: commit
      run: |
        # Stage the file, commit and push
        git add *
        git commit -m "Build Resources"
        git push origin master
