name: Page Automator

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 15.x ]

    steps:
      - uses: actions/checkout@master
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM Install
        run: |
          npm i -g markdown-html-gen
          npm i -g minify

      - name: setup git config
        run: |
          git config user.name "Hoarfroster Bot"
          git config user.email "<penguin.zhang@qq.com>"

      - name: Generate HTML Pages with Markdown Files
        run: |
          for f in documents/*.md
            do
              htmlpath=${f/documents/archive}
              htmlpath=${htmlpath/md/html}
              if [ ! -f htmlpath ]; then
                md2html "$f" -o ./archive
                echo "Generated $htmlpath"
              fi
            done

      - name: Commit Generated HTML Pages
        run: |
          if [[ -n $(git status -uno --porcelain) ]]
          then
            git add *
            git commit -m "Build Pages"
            git push origin master --force
          fi
